name: ci-test

on: 
  push: 
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

    test:
        name: Test
        runs-on: ubuntu-latest

        # 使用外部服务
        services: 
          postgres:
            image: postgres:15.6
            env:
              POSTGRES_USER: root
              POSTGRES_PASSWORD: root
              POSTGRES_DB: simple_bank
            options: >-
              --health-cmd pg_isready



        steps:
          - name: Set up Go 1.x
            uses: actions/setup-go@v5
            with:
                go-version: '>=1.20'
            id: go

          - name: Check out code into the Go module directory
            uses: actions/checkout@v4

          - name: Run migrations
            run: make migrateup

          - name: Test
            run: make test

          
              